%CVzy.cls
%
%	Produced by 0p3r4t0r

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%------------Latex Basics-------------%
\LoadClassWithOptions{article}
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{CVzy}[2017/01/02]

%---------Required Packages-----------%
\RequirePackage[margin=2.0cm]{geometry}			%Set document margins
\RequirePackage{graphicx}									%Allow graphics
\graphicspath{ {./CVzy.icons} }
\RequirePackage[CJK]{ruby}								%Insert fuirgana
\renewcommand\rubysep{0.1ex}
\renewcommand{\rubysize}{0.6}



